language: android
sudo: required
jdk: oraclejdk8
android:
  components:
    - build-tools-27.0.3
    - android-27
  licenses:
    - android-sdk-preview-license-.+
    - android-sdk-license-.+
    - google-gdk-license-.+
before_install:
  - mv ./licenses "$ANDROID_HOME/licenses"
  - chmod +x gradlew
  - ./gradlew dependencies || true
